### ISSUE TITLE
ensure `update-versions.sh` scripts account for dependencies with `-cu{CUDA_MAJOR}` suffixes

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/build-planning#13]
## Overview

RAPIDS projects are released on the same cadence, mostly using the same versioning scheme, as described in https://docs.rapids.ai/releases/process/.

Given that, the projects tend to have dependencies on other RAPIDS projects from the same release. For example, like this in a `pyproject.toml`:

```toml
[project]
# ...
dependencies = [
    "cudf==24.2.*",
    # ...
    "dask-cuda==24.2.*",
    "dask-cudf==24.2.*",
    # ...
    "pylibraft==24.2.*",
    "raft-dask==24.2.*",
    "rapids-dask-dependency==24.2.*",
    "rmm==24.2.*"
]
```

([cuml code link](https://github.com/rapidsai/cuml/blob/a93040c19f214d7f2a8e47e0cdd74cdbe3b83eeb/python/pyproject.toml#L47-L71)).

When cutting a new release, shell scripts in each repo (by convention, `ci/release/update-version.sh`) are used to update all such versions to the newest RAPIDS release.

As of this writing, some of those scripts don't account for projects whose names have a `-cu{CUDA_MAJOR}` suffix in the name, like this:

```text
cudf-cu12==24.2.*
```

As a result, some dependencies may be missed when beginning a new release cycle.

That should be fixed.

## Approach

1. review the discussion in https://github.com/rapidsai/cudf/pull/14825 and https://github.com/rapidsai/cuml/pull/5726
2. make similar changes on the `branch-24.04` branches of all other RAPIDS repos
