### ISSUE TITLE
Use SPDX license tags in pyproject.toml

### ISSUE THREAD

**Issue by bdice** [rapidsai/build-planning#152]
We want to use [SPDX license identifiers](https://spdx.org/licenses/) in `pyproject.toml` files, following [the Python Packaging Docs on the `license` field](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license).

Today we define our licenses in a way that was meant to pass wheeltamer, an internal check for wheels which is no longer used.

Therefore we should replace this:
```toml
[project]
license = { text = "Apache 2.0" }
```

with this (note the dash, which makes this a valid SPDX identifier):
```toml
[project]
license = "Apache-2.0"
```
